### PR TITLE
Cloud Tasks sample

### PR DESCRIPTION
**Pull request by kostacasa**
Opening this early to get some feedback. The queue and task creation works flawlessly, but I ran into issues when attempting to convert `Queue` and `Task` classes into strings. 

At runtime, the natively built image would fail complaining about getters not being found, both within the class in question and the builder, for example `Queue$Builder`.  This is, presumably, because the way gRPC classes are converted to strings requires reflective access. For example, the Task object is printed like this:

```
name: "projects/xxxxxxxx/locations/us-central1/queues/graal-test-queue-6685/tasks/56217623861818533241"
http_request {
  url: "https://google.com/"
  http_method: GET
  headers {
    key: "User-Agent"
    value: "Google-Cloud-Tasks"
  }
}
schedule_time {
  seconds: 1613187863
  nanos: 685055000
}
create_time {
  seconds: 1613187863
}
dispatch_deadline {
  seconds: 600
}
view: BASIC
```

As you can see, it also prints some timestamps and durations. Because it uses `com.google.protobuf.Duration` and `com.google.protobuf.Timestamp` classes to represent those values, I also got a runtime crash complaining that the getters for those classes were not available within the corresponding static Builders. 

This is why I changed the `GrpcNettyFeature` to include both and register the whole hierarchy in order to include their static Builder classes.

If you feel that this falls outside the scope of creating a Cloud Tasks sample, let me know. I think it might be worthwhile attempting to print out more of the classes in the other samples and see if same issues apply. Alternatively, if you don't wish to support `toString()` conversions for the classes, I could take this out entirely and just focus on the Tasks sample.

### CODE REVIEW

**Comment by dzou** [comment]
@kostacasa -- Hey thanks for the contribution! Will take a look at this shortly.

**Comment by dzou** [comment]
Thanks @kostacasa -- This is really great! I added some polish changes, will merge in when the build passes.

I see you had to `registerPackageForReflection(access, "com.google.cloud.tasks.v2");` because printing the protos required reflection. I'll do some research see if we can come up with a reduced filter for what classes need to be registered there (maybe we might be able to limit it to only classes where the `TextFormat.print` is called or something similar).

**Comment by dzou** [comment]
> I want to say I didn't use UUID because I got an error that the name is too long or something of the sort, but we'll find out once the tests run! :)

Ohh gotcha, yeah let's see if it is an issue.

**Comment by kostacasa** [comment]
> I see you had to `registerPackageForReflection(access, "com.google.cloud.tasks.v2");` because printing the protos required reflection. I'll do some research see if we can come up with a reduced filter for what classes need to be registered there (maybe we might be able to limit it to only classes where the `TextFormat.print` is called or something similar).

That's right, it was a bit of a sledgehammer approach in fairness. I agree it would be more desirable to be specific to keep the resulting artifacts as lightweight as possible. If there is a better approach, it would be worthwhile investigating since all the libraries would benefit from this capability.

**Comment by dzou** [comment]
> That's right, it was a bit of a sledgehammer approach in fairness. I agree it would be more desirable to be specific to keep the resulting artifacts as lightweight as possible. If there is a better approach, it would be worthwhile investigating since all the libraries would benefit from this capability.

No worries, I think this is a good start. I have some ideas for how to improve on this which I'll followup with next week.

Thank you again for your time on this!

**Review by dzou — APPROVED** [review]

**Pull request merged**
